# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code 
#  For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: UI build

on:
  push:
    branches: [ "main" ]
    paths:
      - ./**
      - .github/**
  pull_request:
    branches: [ "main" ]
    paths:
      - ./**
      - .github/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Audit packages
        run: npm audit --production --audit-level=high
      - name: Install packages
        run: npm ci
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      # - name: Test
      #   run: npm run test:ci

